// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.b_velop.coffee_O_mat.Persistence.Context;

namespace com.b_velop.coffee_O_mat.Persistence.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20200510122737_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("com.b_velop.coffee_O_mat.Domain.Models.Brew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<double>("KD")
                        .HasColumnType("REAL");

                    b.Property<double>("KI")
                        .HasColumnType("REAL");

                    b.Property<double>("KP")
                        .HasColumnType("REAL");

                    b.Property<double>("Output")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetTemperature")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Brews");
                });
#pragma warning restore 612, 618
        }
    }
}
